version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  check:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - store_artifacts:
          path: app/build/reports/
  test:
    override:
      - scripts/saddler.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - check
